const menu = [
  {
    name: "Blue T-shirt",
    img: "kkkkkkkk.jpg",
    price: 5,
    Kids: true,
    Adult: false,
    Summer: true,
    winter: false,
    Designer: false,
    All: true,
  },
  {
    name: "Green T-shirt",
    img: "greent.jpg",
    price: 8,
    Kids: true,
    Adult: false,
    Summer: true,
    winter: false,
    Designer: false,
    All: true,
  },
  {
    name: "Pink Hoodie",
    img: "rttrsrk.jpg",
    price: 23,
    Kids: true,
    Adult: false,
    Summer: false,
    winter: true,
    Designer: false,
    All: true,
  },
  {
    name: "Red Coat",
    img: "kgfkfg.jpg",
    price: 78,
    Kids: false,
    Adult: true,
    Summer: false,
    winter: true,
    Designer: false,
    All: true,
  },
  {
    name: "Louie V shirt",
    img: "iupipupiu.jpg",
    price: 1062,
    Kids: false,
    Adult: true,
    Summer: true,
    winter: false,
    Designer: true,
    All: true,
  },
  {
    name: "Supreme Hoodie",
    img: "jjjjjjjjjjj.jpg",
    price: 2678,
    Kids: true,
    Adult: true,
    Summer: false,
    winter: true,
    Designer: true,
    All: true,
  },
  {
    name: "Bape Hoodie",
    img: "hhhhhhhh.jpg",
    price: 3099,
    Kids: false,
    Adult: true,
    Summer: false,
    winter: true,
    Designer: true,
    All: true,
  },
  {
    name: "Yellow Coat",
    img: "lllllllllllllllllllllll.jpg",
    price: 347,
    Kids: false,
    Adult: true,
    Summer: false,
    winter: true,
    Designer: false,
    All: true,
  },
  {
    name: "Taxes Shirt",
    img: "66666.jpg",
    price: 37,
    Kids: false,
    Adult: true,
    Summer: true,
    winter: false,
    Designer: false,
    All: true,
  },
  {
    name: "Striped Shirt",
    img: "yyyyyyy.jpg",
    price: 15,
    Kids: true,
    Adult: false,
    Summer: true,
    winter: false,
    Designer: false,
    All: true,
  },
  {
    name: "Gucci Coat",
    img: "22222222.jpg",
    price: 5629,
    Kids: false,
    Adult: true,
    Summer: false,
    winter: true,
    Designer: true,
    All: true,
  },
  {
    name: "Awesome Shirt",
    img: "uuuuuuuuuuu.jpg",
    price: 22,
    Kids: true,
    Adult: false,
    Summer: true,
    winter: false,
    Designer: false,
    All: true,
  },
];
export { menu };
